Sets

j macro-regions
/
metropolitana-salvador
nordeste
sul
extremo-oeste
vale-do-sao-francisco
centro-norte
centro-sul
/

k micro-regions
/
r-santo-antonio-de-jesus
r-salvador
r-catu
r-euclides-da-cunha
r-jeremoabo
r-ribeira-do-pombal
r-alagoinhas
r-entre-rios
r-serrinha
r-valenca
r-ilheus-itabuna
r-porto-seguro
r-barreiras
r-santa-maria-da-vitoria
r-cotegipe
r-barra
r-bom-jesus-da-lapa
r-juazeiro
r-paulo-afonso
r-senhor-do-bonfim
r-irece
r-jacobina
r-itaberaba
r-feira-de-santana
r-boquira
r-guanambi
r-seabra
r-livramento-de-nossa-senhora
r-brumado
r-itapetinga
r-vitoria-da-conquista
r-jequie
/

macroCluster(j,k)
/
centro-norte.(r-feira-de-santana,r-irece,r-itaberaba,r-jacobina,r-senhor-do-bonfim)
centro-sul.(r-boquira,r-brumado,r-guanambi,r-itapetinga,r-jequie,r-livramento-de-nossa-senhora,r-seabra,r-vitoria-da-conquista)
extremo-oeste.(r-barreiras,r-cotegipe,r-santa-maria-da-vitoria)
metropolitana-salvador.(r-catu,r-salvador,r-santo-antonio-de-jesus)
nordeste.(r-alagoinhas,r-entre-rios,r-euclides-da-cunha,r-jeremoabo,r-ribeira-do-pombal,r-serrinha)
sul.(r-ilheus-itabuna,r-porto-seguro,r-valenca)
vale-do-sao-francisco.(r-barra,r-bom-jesus-da-lapa,r-juazeiro,r-paulo-afonso)
/

i cities
/
jaguaripe
aratuipe
nazare
muniz-ferreira
santo-antonio-de-jesus
varzedo
castro-alves
conceicao-do-almeida
dom-macedo-costa
sao-felipe
maragogipe
salinas-da-margarida
sapeacu
cruz-das-almas
cabaceiras-do-paraguacu
governador-mangabeira
muritiba
sao-felix
saubara
cachoeira
santo-amaro
sao-francisco-do-conde
madre-de-deus
salvador
itaparica
vera-cruz
candeias
simoes-filho
lauro-de-freitas
dias-davila
camacari
itanagra
mata-de-sao-joao
catu
pojuca
sao-sebastiao-do-passe
terra-nova
amelia-rodrigues
cansancao
canudos
euclides-da-cunha
monte-santo
nordestina
queimadas
quijingue
tucano
uaua
jeremoabo
coronel-joao-sa
pedro-alexandre
santa-brigida
sitio-do-quinto
paripiranga
adustina
antas
banzae
cicero-dantas
cipo
fatima
heliopolis
itapicuru
nova-soure
novo-triunfo
olindina
ribeira-do-amparo
ribeira-do-pombal
acajutiba
alagoinhas
apora
aracas
aramari
crisopolis
inhambupe
rio-real
satiro-dias
cardeal-da-silva
conde
entre-rios
esplanada
jandaira
araci
barrocas
biritinga
candeal
capela-do-alto-alegre
conceicao-do-coite
gaviao
ichu
lamarao
nova-fatima
pe-de-serra
retirolandia
riachao-do-jacuipe
santaluz
sao-domingos
serrinha
teofilandia
valente
cairu
camamu
igrapiuna
itubera
marau
nilo-pecanha
pirai-do-norte
presidente-tancredo-neves
taperoa
valenca
almadina
arataca
aurelino-leal
barra-do-rocha
barro-preto
belmonte
buerarema
camacan
canavieiras
coaraci
firmino-alves
floresta-azul
gandu
gongogi
ibicarai
ibirapitanga
ibirataia
ilheus
ipira
itabuna
itacare
itagiba
itaju-do-colonia
itajuipe
itamari
itape
itapebi
itapitanga
jussari
mascote
nova-ibia
pau-brasil
santa-cruz-da-vitoria
santa-luzia
sao-jose-da-vitoria
teolandia
ubaitaba
ubata
una
urucuca
wenceslau-guimaraes
alcobaca
caravelas
eunapolis
guaratinga
ibirapua
itabela
itagimirim
itamaraju
itanhem
jucurucu
lajedao
medeiros-neto
mucuri
nova-vicosa
porto-seguro
prado
santa-cruz-cabralia
teixeira-de-freitas
vereda
barreiras
baianopolis
catolandia
formosa-do-rio-preto
luis-eduardo-magalhaes
sao-desiderio
riachao-das-neves
canapolis
cocos
coribe
correntina
jaborandi
santa-maria-da-vitoria
santana
sao-felix-do-coribe
serra-dourada
angical
brejolandia
cotegipe
cristopolis
mansidao
santa-rita-de-cassia
tabocas-do-brejo-velho
wanderley
barra
buritirama
ibotirama
itaguacu-da-bahia
morpara
muquem-de-sao-francisco
xique-xique
bom-jesus-da-lapa
carinhanha
feira-da-mata
paratinga
serra-do-ramalho
sitio-do-mato
campo-alegre-de-lourdes
casa-nova
curaca
juazeiro
pilao-arcado
remanso
sento-se
sobradinho
abare
chorrocho
gloria
macurure
paulo-afonso
rodelas
andorinha
antonio-goncalves
campo-formoso
filadelfia
itiuba
jaguarari
pindobacu
senhor-do-bonfim
umburanas
america-dourada
barra-do-mendes
barro-alto
cafarnaum
canarana
central
gentio-do-ouro
ibipeba
ibitita
iraquara
irece
joao-dourado
jussara
lapao
mulungu-do-morro
presidente-dutra
sao-gabriel
souto-soares
uibai
caem
caldeirao-grande
capim-grosso
jacobina
miguel-calmon
mirangaba
morro-do-chapeu
ourolandia
piritiba
ponto-novo
quixabeira
sao-jose-do-jacuipe
saude
serrolandia
varzea-do-poco
varzea-nova
baixa-grande
boa-vista-do-tupim
iacu
ibiquera
itaberaba
lajedinho
macajuba
mairi
mundo-novo
ruy-barbosa
tapiramuta
varzea-da-roca
agua-fria
anguera
antonio-cardoso
conceicao-da-feira
conceicao-do-jacuipe
coracao-de-maria
elisio-medrado
feira-de-santana
ipecaeta
ipiau
irara
itatim
ouricangas
pedrao
pintadas
rafael-jambeiro
santa-barbara
santa-teresinha
santanopolis
santo-estevao
sao-goncalo-dos-campos
serra-preta
tanquinho
teodoro-sampaio
boquira
botupora
brotas-de-macaubas
caturama
ibipitanga
ibitiara
ipupiara
macaubas
novo-horizonte
oliveira-dos-brejinhos
tanque-novo
cacule
caetite
candiba
guanambi
ibiassuce
igapora
iuiu
jacaraci
lagoa-real
licinio-de-almeida
malhada
matina
mortugaba
palmas-de-monte-alto
pindai
riacho-de-santana
sebastiao-laranjeiras
urandi
abaira
andarai
barra-da-estiva
boninal
bonito
contendas-do-sincora
ibicoara
itaete
jussiape
lencois
mucuge
nova-redencao
palmeiras
piata
rio-de-contas
seabra
utinga
wagner
dom-basilio
erico-cardoso
livramento-de-nossa-senhora
paramirim
rio-do-pires
aracatu
brumado
caraibas
condeuba
cordeiros
guajeru
ituacu
maetinga
malhada-de-pedras
piripa
presidente-janio-quadros
rio-do-antonio
tanhacu
tremedal
encruzilhada
itambe
itapetinga
itarantim
itororo
macarani
maiquinique
potiragua
ribeirao-do-largo
anage
barra-do-choca
belo-campo
boa-nova
bom-jesus-da-serra
caatiba
caetanos
candido-sales
dario-meira
ibicui
iguai
manoel-vitorino
mirante
nova-canaa
planalto
pocoes
vitoria-da-conquista
aiquara
amargosa
apuarema
brejoes
cravolandia
irajuba
iramaia
itagi
itaquara
itirucu
jaguaquara
jequie
jitauna
lafaiete-coutinho
laje
lajedo-do-tabocal
maracas
marcionilio-souza
milagres
mutuipe
nova-itarana
planaltino
santa-ines
sao-miguel-das-matas
ubaira
jiquirica
/

microCluster(k,i)
/
r-feira-de-santana.(agua-fria,anguera,antonio-cardoso,conceicao-da-feira,conceicao-do-jacuipe,coracao-de-maria,elisio-medrado,feira-de-santana,ipecaeta,ipira,irara,itatim,ouricangas,pedrao,pintadas,rafael-jambeiro,santa-barbara,santa-teresinha,santanopolis,santo-estevao,sao-goncalo-dos-campos,serra-preta,tanquinho,teodoro-sampaio)
r-irece.(america-dourada,barra-do-mendes,barro-alto,cafarnaum,canarana,central,gentio-do-ouro,ibipeba,ibitita,iraquara,irece,joao-dourado,jussara,lapao,mulungu-do-morro,presidente-dutra,sao-gabriel,souto-soares,uibai)
r-itaberaba.(baixa-grande,boa-vista-do-tupim,iacu,ibiquera,itaberaba,lajedinho,macajuba,mairi,mundo-novo,ruy-barbosa,tapiramuta,varzea-da-roca)
r-jacobina.(caem,caldeirao-grande,capim-grosso,jacobina,miguel-calmon,mirangaba,morro-do-chapeu,ourolandia,piritiba,ponto-novo,quixabeira,sao-jose-do-jacuipe,saude,serrolandia,varzea-do-poco,varzea-nova)
r-senhor-do-bonfim.(andorinha,antonio-goncalves,campo-formoso,filadelfia,itiuba,jaguarari,pindobacu,senhor-do-bonfim,umburanas)
r-boquira.(boquira,botupora,brotas-de-macaubas,caturama,ibipitanga,ibitiara,ipupiara,macaubas,novo-horizonte,oliveira-dos-brejinhos,tanque-novo)
r-brumado.(aracatu,brumado,caraibas,condeuba,cordeiros,guajeru,ituacu,maetinga,malhada-de-pedras,piripa,presidente-janio-quadros,rio-do-antonio,tanhacu,tremedal)
r-guanambi.(cacule,caetite,candiba,guanambi,ibiassuce,igapora,iuiu,jacaraci,lagoa-real,licinio-de-almeida,malhada,matina,mortugaba,palmas-de-monte-alto,pindai,riacho-de-santana,sebastiao-laranjeiras,urandi)
r-itapetinga.(encruzilhada,itambe,itapetinga,itarantim,itororo,macarani,maiquinique,potiragua,ribeirao-do-largo)
r-jequie.(aiquara,amargosa,apuarema,brejoes,cravolandia,irajuba,iramaia,itagi,itaquara,itirucu,jaguaquara,jequie,jiquirica,jitauna,lafaiete-coutinho,laje,lajedo-do-tabocal,maracas,marcionilio-souza,milagres,mutuipe,nova-itarana,planaltino,santa-ines,sao-miguel-das-matas,ubaira)
r-livramento-de-nossa-senhora.(dom-basilio,erico-cardoso,livramento-de-nossa-senhora,paramirim,rio-do-pires)
r-seabra.(abaira,andarai,barra-da-estiva,boninal,bonito,contendas-do-sincora,ibicoara,itaete,jussiape,lencois,mucuge,nova-redencao,palmeiras,piata,rio-de-contas,seabra,utinga,wagner)
r-vitoria-da-conquista.(anage,barra-do-choca,belo-campo,boa-nova,bom-jesus-da-serra,caatiba,caetanos,candido-sales,dario-meira,ibicui,iguai,manoel-vitorino,mirante,nova-canaa,planalto,pocoes,vitoria-da-conquista)
r-barreiras.(baianopolis,barreiras,catolandia,formosa-do-rio-preto,luis-eduardo-magalhaes,riachao-das-neves,sao-desiderio)
r-cotegipe.(angical,brejolandia,cotegipe,cristopolis,mansidao,santa-rita-de-cassia,tabocas-do-brejo-velho,wanderley)
r-santa-maria-da-vitoria.(canapolis,cocos,coribe,correntina,jaborandi,santa-maria-da-vitoria,santana,sao-felix-do-coribe,serra-dourada)
r-catu.(amelia-rodrigues,catu,itanagra,mata-de-sao-joao,pojuca,sao-sebastiao-do-passe,terra-nova)
r-salvador.(camacari,candeias,dias-davila,itaparica,lauro-de-freitas,madre-de-deus,salvador,sao-francisco-do-conde,simoes-filho,vera-cruz)
r-santo-antonio-de-jesus.(aratuipe,cabaceiras-do-paraguacu,cachoeira,castro-alves,conceicao-do-almeida,cruz-das-almas,dom-macedo-costa,governador-mangabeira,jaguaripe,maragogipe,muniz-ferreira,muritiba,nazare,salinas-da-margarida,santo-amaro,santo-antonio-de-jesus,sao-felipe,sao-felix,sapeacu,saubara,varzedo)
r-alagoinhas.(acajutiba,alagoinhas,apora,aracas,aramari,crisopolis,inhambupe,rio-real,satiro-dias)
r-entre-rios.(cardeal-da-silva,conde,entre-rios,esplanada,jandaira)
r-euclides-da-cunha.(cansancao,canudos,euclides-da-cunha,monte-santo,nordestina,queimadas,quijingue,tucano,uaua)
r-jeremoabo.(coronel-joao-sa,jeremoabo,pedro-alexandre,santa-brigida,sitio-do-quinto)
r-ribeira-do-pombal.(adustina,antas,banzae,cicero-dantas,cipo,fatima,heliopolis,itapicuru,nova-soure,novo-triunfo,olindina,paripiranga,ribeira-do-amparo,ribeira-do-pombal)
r-serrinha.(araci,barrocas,biritinga,candeal,capela-do-alto-alegre,conceicao-do-coite,gaviao,ichu,lamarao,nova-fatima,pe-de-serra,retirolandia,riachao-do-jacuipe,santaluz,sao-domingos,serrinha,teofilandia,valente)
r-ilheus-itabuna.(almadina,arataca,aurelino-leal,barra-do-rocha,barro-preto,belmonte,buerarema,camacan,canavieiras,coaraci,firmino-alves,floresta-azul,gandu,gongogi,ibicarai,ibirapitanga,ibirataia,ilheus,ipiau,itabuna,itacare,itagiba,itaju-do-colonia,itajuipe,itamari,itape,itapebi,itapitanga,jussari,mascote,nova-ibia,pau-brasil,santa-cruz-da-vitoria,santa-luzia,sao-jose-da-vitoria,teolandia,ubaitaba,ubata,una,urucuca,wenceslau-guimaraes)
r-porto-seguro.(alcobaca,caravelas,eunapolis,guaratinga,ibirapua,itabela,itagimirim,itamaraju,itanhem,jucurucu,lajedao,medeiros-neto,mucuri,nova-vicosa,porto-seguro,prado,santa-cruz-cabralia,teixeira-de-freitas,vereda)
r-valenca.(cairu,camamu,igrapiuna,itubera,marau,nilo-pecanha,pirai-do-norte,presidente-tancredo-neves,taperoa,valenca)
r-barra.(barra,buritirama,ibotirama,itaguacu-da-bahia,morpara,muquem-de-sao-francisco,xique-xique)
r-bom-jesus-da-lapa.(bom-jesus-da-lapa,carinhanha,feira-da-mata,paratinga,serra-do-ramalho,sitio-do-mato)
r-juazeiro.(campo-alegre-de-lourdes,casa-nova,curaca,juazeiro,pilao-arcado,remanso,sento-se,sobradinho)
r-paulo-afonso.(abare,chorrocho,gloria,macurure,paulo-afonso,rodelas)
/

s scenarios
/1*3/

socialIdx social indices 
/unemployment,	electrics,	walls,	water,	illiteracy,	fgt,	elderly /

;

*'Alias for the set of cities i'
Alias(i,l);
Alias(k,k2);

